### ISSUE TITLE
Enhancement: Build a full imsmanifest.xml file

### ISSUE THREAD

**Issue by bredd** [SmarterApp/AP_BuildSmarterContentPackage#2]
Presently, the builder includes an empty imsmanifest.xml file. That's because some tools, such as the tabulator, check for the file's presence as an indicator that this is a test package. So far, no tools actually make use of the manifest contents. On the possibility that future tools may need this information, this enhancement would be to fill in the manifest.

**Comment by alexdean201** [comment]
Versions >2.4 include the ability to build a full imsmanifest.xml file.
